env:
  browser: true
  es6: true
extends:
  - "plugin:prettier/recommended"
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: "latest"
  sourceType: module
rules: {}
